# Generated by Django 5.1.7 on 2025-04-05 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leave.leave'),
        ),
    ]
